
## Day objective
    - Numpy
        - numpy stands for numeric python
        - using for scientific calculations
        - and also for processing multidiamensional array
        - this is external module so 'import numpy'
        - it is library build with c
        - for installing numpy 'pip install numpy'
        - less memory,faster 

In [1]:
import numpy as np

In [2]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__packag

In [12]:
arr = np.array([1,2,3,4])

In [13]:
arr

array([1, 2, 3, 4])

In [14]:
li =[1,5,6,9]

In [15]:
type(li)

list

In [8]:
li=np.array(li)

In [9]:
type(li)

numpy.ndarray

In [10]:
li

array([1, 5, 6, 9])

In [11]:
t=(1,2,2,3)

In [12]:
t=np.array(t)

In [13]:
type(t)

numpy.ndarray

In [14]:
t


array([1, 2, 2, 3])

In [1]:
l1=range(1,500)


In [4]:
l1[3]

4

In [17]:
len(l1)

499

In [18]:
import sys

In [23]:
sys.getsizeof(l1)

48

In [24]:
arr = np.arange(1,500)

In [25]:
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [26]:
len(arr)

499

In [27]:
arr.itemsize

4

In [29]:
%%timeit -n 1
print(1)

1
1
1
1
1
1
1
The slowest run took 16.60 times longer than the fastest. This could mean that an intermediate result is being cached.
46.9 µs ± 50.1 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [30]:
import time


In [31]:
t= time.time()
t

1577695016.719337

In [33]:
l1

range(1, 500)

In [48]:
import time
stime=time.time()
l1=range(10000000)
for i in l1:
    i+=2
    #print(i+2,end=",")
etime=time.time()
print((stime-etime)*1000)

-857.7370643615723


In [41]:
arr+2

array([  3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,
        16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
        42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,
        55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,
        68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,
        81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
        94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106,
       107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119,
       120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
       133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
       146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158,
       159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171,
       172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 18

In [49]:
arr= np.arange(10000000)
stime=time.time()
arr+2
etime=time.time()
print((stime-etime)*1000)

-25.99310874938965


## differnt ways to generate arrays
- array()
- arange()
 -linspace()
- logspace()
- ones()
- zeros()

In [2]:
a1= np.array([1,2,3,4])

In [3]:
a1=np.array(range(500))

In [4]:
a1

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [58]:
a2= np.arange(1,10)

In [59]:
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
a3= np.linspace(1,10)

In [6]:
a3

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [7]:
a2=np.arange(1,10,20)

In [8]:
a2

array([1])

In [9]:
np.logspace(1,10,20)

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [10]:
np.logspace(1,10)

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

In [67]:
np.ones((1,5))

array([[1., 1., 1., 1., 1.]])

In [68]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [70]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [71]:
a1= np.array([1,2,3,4,5])

In [72]:
a1

array([1, 2, 3, 4, 5])

In [73]:
a1= np.array([1,2,3,4,5.23])
a1

array([1.  , 2.  , 3.  , 4.  , 5.23])

In [74]:
a1= np.array([1,2,3,4,5.25],dtype=int)
a1

array([1, 2, 3, 4, 5])

In [75]:
np.array([1,2,3,4,5],dtype=float)

array([1., 2., 3., 4., 5.])

In [76]:
arr=np.arange(1,20)

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [79]:
arr=arr+2

In [81]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [82]:
arr=arr-2

In [83]:
arr

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
       16, 17])

In [84]:
arr=arr/2

In [85]:
arr

array([-0.5,  0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,
        5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5])

In [86]:
arr=arr//2

In [87]:
arr

array([-1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,
        3.,  3.,  3.,  3.,  4.,  4.])

In [88]:
arr=arr **2

In [89]:
arr

array([ 1.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,  4.,  4.,  4.,  4.,
        9.,  9.,  9.,  9., 16., 16.])

In [90]:
arr = np.array([range(1,4),range(4,7)])

In [91]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [92]:
ar =np.arange(10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
ar.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [94]:
ar.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [3]:
import numpy as np
arr= np.arange(25).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [2]:
arr= np.arange(1,10).reshape(3,3)

In [3]:
arr.sum()
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [104]:
# to add the column wise
arr.sum(1)

array([ 6, 15, 24])

In [105]:
#to add the  row wise
arr.sum(0)

array([12, 15, 18])

In [4]:
arr.max()

9

In [5]:
arr.min()

1

In [108]:
arr.max(1) # it returns row wise max element

array([3, 6, 9])

In [110]:
arr.min(1) # it returns row wise min element

array([1, 4, 7])

In [8]:
arr.max(0)# it returns column wise max element

array([7, 8, 9])

In [114]:
arr.min(axis=0)# it returns column wise max element

array([1, 2, 3])

NameError: name 'input1' is not defined

In [2]:
(2+1)%5

3