In [1]:
import numpy as np
names = ['raj','anil','raj']
names = np.array(names)
data= np.arange(1,4)

In [3]:
names =='raj'

array([ True, False,  True])

In [7]:
data[names=='raj']

array([1, 3])

In [12]:
data[(names=='raj') | (names == 'anil')]

array([1, 2, 3])

In [13]:
data.cumsum()

array([1, 3, 6], dtype=int32)

In [17]:
data.cumprod().reshape(1,3)

array([[1, 2, 6]], dtype=int32)

In [18]:
a=np.arange(1,26).reshape(5,5)

In [19]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
a.cumsum(0)

array([[ 1,  2,  3,  4,  5],
       [ 7,  9, 11, 13, 15],
       [18, 21, 24, 27, 30],
       [34, 38, 42, 46, 50],
       [55, 60, 65, 70, 75]], dtype=int32)

In [21]:
ar1=np.random.randn(3,3)

In [22]:
ar1

array([[ 1.05820039, -1.16413124,  0.15749765],
       [-0.27890182,  0.608181  , -0.19179407],
       [-0.16450766, -0.95202693, -0.58574704]])

In [23]:
ar1.sort()

In [24]:
ar1

array([[-1.16413124,  0.15749765,  1.05820039],
       [-0.27890182, -0.19179407,  0.608181  ],
       [-0.95202693, -0.58574704, -0.16450766]])

In [25]:
ar1.sort(0)

In [26]:
ar1

array([[-1.16413124, -0.58574704, -0.16450766],
       [-0.95202693, -0.19179407,  0.608181  ],
       [-0.27890182,  0.15749765,  1.05820039]])

## pandas
    - pandas for data analysis and data manipulation(data clean)
    - for installing pandas "pip install pandas"
    - in pandas ther two differnt datastructes
        - series
        - data frame
        

import pandas as pd


## series 
    - it is data structres
    - we casn use series for generating one diamensional array with different datatypes
    - we have different ways for creating series
        - Array
        - list
        - tuples
        - dictionaries

In [30]:
arr = np.arange(1,6)
s1 =pd.Series(arr)
s1

0    1
1    2
2    3
3    4
4    5
dtype: int32

In [31]:
list =[ 'gokul','upendra','srikanth','sai']
s2= pd.Series(list)

In [32]:
s2

0       gokul
1     upendra
2    srikanth
3         sai
dtype: object

In [33]:
data ={'names':['sunil','anil','ramu'],'rollno':['1','2','3']}

In [34]:
s3= pd.Series(data)

In [35]:
s3

names     [sunil, anil, ramu]
rollno              [1, 2, 3]
dtype: object

In [37]:
s1,s2

(0    1
 1    2
 2    3
 3    4
 4    5
 dtype: int32, 0       gokul
 1     upendra
 2    srikanth
 3         sai
 dtype: object)

In [40]:
# changing index position
arr =np.arange(1,11)
ind =['a','b','c','d','e','f','g','h','i','j']
sr = pd.Series(arr,index=ind)
sr

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int32

In [41]:
# acessing series elements
# based on elements
# based on index positions
sr[0]

1

In [43]:
sr['a']

1

In [44]:
sr

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int32

In [49]:
sr.loc['b']

2

In [50]:
sr.iloc[0]

1

In [51]:
sr.iloc[[0,2,4,6]]

a    1
c    3
e    5
g    7
dtype: int32

In [52]:
sr.loc[['a','b']]

a    1
b    2
dtype: int32

## series operations 

In [53]:
sr.mean()

5.5

In [54]:
sr.var()

9.166666666666666

In [55]:
sr.max()

10

In [56]:
sr.min()

1

In [57]:
sr.sum()

55

In [58]:
sr.std()

3.0276503540974917

In [60]:
sr.head()

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
dtype: int32

In [61]:
sr.head(8)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int32

In [62]:
sr.tail()

f     6
g     7
h     8
i     9
j    10
dtype: int32

In [63]:
sr.tail(3)

h     8
i     9
j    10
dtype: int32

## series attributes

In [65]:
sr.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [66]:
sr.values

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [67]:
sr.size

10

In [68]:
sr.itemsize

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Series.itemsize is deprecated and will be removed in a future version
  """Entry point for launching an IPython kernel.


4

In [69]:
sr.dtype

dtype('int32')

In [70]:
s2=pd.Series([1,2,3,4],dtype='int64')

In [71]:
s2

0    1
1    2
2    3
3    4
dtype: int64

In [72]:
s2.size

4

In [73]:
s2.itemsize

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Series.itemsize is deprecated and will be removed in a future version
  """Entry point for launching an IPython kernel.


8