In [1]:
import numpy as np
import pandas as pd


In [3]:
#Write a Pandas program to change the column names of a data frame.
names = ['gokul','raju','ravi']
rollnos=[500,501,502]
d1={'Names':names,'Rollno':rollnos}
df=pd.DataFrame(d1)
df

Names  Rollno
0  gokul     500
1   raju     501
2   ravi     502

In [4]:
df.columns=['id name','id rollno']
df

id name  id rollno
0   gokul        500
1    raju        501
2    ravi        502

In [5]:
#. Write a Python program to add, subtract, multiple and divide two Pandas      
 #   Series.
  # Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

d1=pd.Series([2, 4, 6, 8, 10])
d2=pd.Series([2, 4, 6, 8, 10])
ds = d1 + d2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = d1 - d2
print(ds)
print("Multiply two Series:")
ds = d1 * d2
print(ds)
print("Divide Series1 by Series2:")
ds = d1 / d2
print(ds)
              

Add two Series:
0     4
1     8
2    12
3    16
4    20
dtype: int64
Subtract two Series:
0    0
1    0
2    0
3    0
4    0
dtype: int64
Multiply two Series:
0      4
1     16
2     36
3     64
4    100
dtype: int64
Divide Series1 by Series2:
0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64


In [7]:
#Write a Python program to convert a Panda module Series to Python list  
 #   and it's type

import pandas as pd
df = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series and type")
print(df)
print(type(df))
print("Convert Pandas Series to Python list")
print(df.tolist())
print(type(df.tolist()))

Pandas Series and type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Convert Pandas Series to Python list
[2, 4, 6, 8, 10]
<class 'list'>


In [16]:
#Write a Pandas program to implement the join,concat and merge after implementing that the resultant could contain NaN values
stu_data=pd.DataFrame({'Name':['gokul','srikanth','kiran'],
                      'Rollno':['5c5','502','539'],
                      'Branch':['CSE','CSE','CSE']})
valid_info=pd.DataFrame({'Name':['gokul','upendra','kiran'],
                        'loveStatus':['yes','yes','yes'],
                        'lovers':[2,2,3]})
df=pd.merge(stu_data,valid_info)
df

Name Rollno Branch loveStatus  lovers
0  gokul    5c5    CSE        yes       2
1  kiran    539    CSE        yes       3

In [15]:
pd.concat([stu_data, valid_info])

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Branch      Name Rollno loveStatus  lovers
0    CSE     gokul    5c5        NaN     NaN
1    CSE  srikanth    502        NaN     NaN
2    CSE     kiran    539        NaN     NaN
0    NaN     gokul    NaN        yes     2.0
1    NaN   upendra    NaN        yes     2.0
2    NaN     kiran    NaN        yes     3.0

In [17]:
pd.merge(stu_data,valid_info,how='left')

Name Rollno Branch loveStatus  lovers
0     gokul    5c5    CSE        yes     2.0
1  srikanth    502    CSE        NaN     NaN
2     kiran    539    CSE        yes     3.0

In [18]:
#Write a Pandas program to create todays date
from datetime import date
now = pd.to_datetime(str(date.today()), format='%Y-%m-%d')
print("Today's date:")
print(now)

Today's date:
2020-01-25 00:00:00


In [24]:
#Write a Pandas program to drop the rows where the score is missing, i.e. 
  #  is NaN 
    

data=pd.DataFrame({'name':['sachin','ganguly','kholi','jhonson','taylor','waugh','yuvaraj','kambali','srinath','munaf'],
'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],
'attempts':[1,3,2,3,2,3,1,1,2,1],
'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes'],
'labels':['a','b','c','d','e','f','g','h','i','j']})
data


name  score  attempts qualify labels
0   sachin   12.5         1     yes      a
1  ganguly    9.0         3      no      b
2    kholi   16.5         2     yes      c
3  jhonson    NaN         3      no      d
4   taylor    9.0         2      no      e
5    waugh   20.0         3     yes      f
6  yuvaraj   14.5         1     yes      g
7  kambali    NaN         1      no      h
8  srinath    8.0         2      no      i
9    munaf   19.0         1     yes      j

In [25]:
#.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [2]:
#Illustrate the difference between ravel and flatten by taking considering multidimensional array
import numpy as np
a = np.array( [ (1,7,3,4),(3,2,4,1) ] )
print( a.flatten() )
print ( a.ravel() )


[1 7 3 4 3 2 4 1]
[1 7 3 4 3 2 4 1]


In [3]:
#. Create a 3×3 numpy array, find out the Minimum,Maximum values and also their indices accordingly for each axes. Also find out the Statistical methods such as Standard Deviation,Cumulative sum and product.
ar2= np.arange(1,10).reshape(3,3)
ar2.mean()

5.0

In [4]:
ar2.var()

6.666666666666667

In [5]:
ar2.sum()

45

In [6]:
ar2.std()

2.581988897471611

In [7]:
ar2.max(0)

array([7, 8, 9])

In [8]:
ar2.min(1)

array([1, 4, 7])

In [5]:
import pandas as pd
  
# Define a dictionary containing students data
data = {'Name': ['Ankit', 'Amit',
                 'Aishwarya', 'Priyanka'],
        'Age': [21, 19, 20, 18],
        'Stream': ['Math', 'Commerce',
                   'Arts', 'Biology'],
        'Percentage': [88, 92, 95, 70]}
  
# Convert the dictionary into DataFrame
df = pd.DataFrame(data, columns=['Name', 'Age',
                                 'Stream', 
                                 'Percentage'])
  
print("Given Dataframe :\n", df)
  
print("\nIterating over rows using loc function :\n")
  
# iterate through each row and select
# 'Name' and 'Age' column respectively.
for i in range(len(df)):
    print(df['Name'][i])

Given Dataframe :
         Name  Age    Stream  Percentage
0      Ankit   21      Math          88
1       Amit   19  Commerce          92
2  Aishwarya   20      Arts          95
3   Priyanka   18   Biology          70

Iterating over rows using loc function :

Ankit
Amit
Aishwarya
Priyanka
