In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1,6)
arr1

array([1, 2, 3, 4, 5])

In [4]:
arr1.mean()

3.0

In [5]:
arr1.var()

2.0

In [6]:
arr1.std()

1.4142135623730951

In [7]:
ar2= np.arange(1,10).reshape(3,3)

In [8]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
ar2.mean()

5.0

In [10]:
ar2.var()

6.666666666666667

In [11]:
ar2.std()

2.581988897471611

In [12]:
ar2.sum(1)

array([ 6, 15, 24])

In [13]:
ar2.sum(0)

array([12, 15, 18])

In [14]:
ar2.mean(1)

array([2., 5., 8.])

In [15]:
ar2.mean(0)

array([4., 5., 6.])

In [16]:
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.dot(ar2,ar2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [20]:
ar2.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [22]:
np.transpose(ar2)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [23]:
np.dot(ar2,ar2.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [3]:
m1 = np.arange(1,5).reshape(2,2)
m2 = np.arange(5,9).reshape(2,2)
m1,m2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [4]:
np.concatenate((m1,m2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
np.concatenate((m1,m2),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [27]:
np.vstack((m1,m2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [7]:
n = np.hstack((m1,m2))
n

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [32]:
n.shape

(2, 4)

In [33]:
arr1.size

5

In [34]:
arr1

array([1, 2, 3, 4, 5])

In [35]:
arr1[:]

array([1, 2, 3, 4, 5])

In [36]:
arr1[1:]

array([2, 3, 4, 5])

In [37]:
arr1[:3]

array([1, 2, 3])

In [38]:
arr1[2:5]

array([3, 4, 5])

In [39]:
n

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [17]:
import numpy as np
m=np.arange(1,26).reshape(5,5)

In [18]:
m

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [20]:
m[:,1]

array([ 2,  7, 12, 17, 22])

In [43]:
m[1,:]

array([ 6,  7,  8,  9, 10])

In [4]:
m[1:,2]

array([ 8, 13, 18, 23])

In [46]:
m[1:,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
m[:,1:]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [50]:
m[:,:-1] # it removes last column

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [52]:
m[:,-2:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

In [53]:
m[1:4,:]# except first and last row

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [54]:
m[1:-1,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [55]:
m[:,1:-1]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [56]:
m[1:-1,1:-1]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [62]:
m[m%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [63]:
np.random

<module 'numpy.random' from 'C:\\Users\\user\\Anaconda3\\lib\\site-packages\\numpy\\random\\__init__.py'>

In [64]:
np.random.random()

0.5272836392676827

In [65]:
np.random.random(5)

array([0.13676558, 0.11686533, 0.34121715, 0.13240848, 0.23202946])

In [71]:
mtr=np.random.random((2,5,3))
mtr

array([[[0.64802735, 0.53691744, 0.70437796],
        [0.25961277, 0.23687711, 0.17760122],
        [0.70910918, 0.0816521 , 0.58645043],
        [0.53132582, 0.05674918, 0.72167024],
        [0.66728655, 0.4242584 , 0.7722395 ]],

       [[0.07362523, 0.03759518, 0.45342507],
        [0.78433439, 0.15047222, 0.2640232 ],
        [0.55606198, 0.27665778, 0.52313456],
        [0.16233424, 0.15174998, 0.52828808],
        [0.05400882, 0.96101174, 0.82278203]]])

In [72]:
mtr+2

array([[[2.64802735, 2.53691744, 2.70437796],
        [2.25961277, 2.23687711, 2.17760122],
        [2.70910918, 2.0816521 , 2.58645043],
        [2.53132582, 2.05674918, 2.72167024],
        [2.66728655, 2.4242584 , 2.7722395 ]],

       [[2.07362523, 2.03759518, 2.45342507],
        [2.78433439, 2.15047222, 2.2640232 ],
        [2.55606198, 2.27665778, 2.52313456],
        [2.16233424, 2.15174998, 2.52828808],
        [2.05400882, 2.96101174, 2.82278203]]])

In [79]:
np.random.randint(10)

9

In [4]:
np.random.randint(5,20,size=10)

array([11, 14, 14, 19,  5,  7,  6, 13, 13, 17])

In [5]:
np.random.randn(2,5)

array([[ 1.16184375, -1.0113888 ,  1.43691265,  0.75369112,  2.32976114],
       [-1.04489709, -0.9551645 ,  0.76564973,  0.83111742,  0.10809556]])